(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")

(depends-on "base16-theme")
(depends-on "cask")
(depends-on "company")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "elixir-mode")
(depends-on "elixir-yasnippets")
(depends-on "epl")
(depends-on "erlang")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flymake-easy")
(depends-on "flymake-elixir")
(depends-on "flymake-haskell-multi")
(depends-on "fuel")
(depends-on "ghc")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "go-autocomplete")
(depends-on "go-mode")
(depends-on "go-snippets")
(depends-on "haskell-mode")
(depends-on "hi2")
(depends-on "highlight-indentation")
(depends-on "idomenu")
(depends-on "iedit")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nose")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "pymacs")
(depends-on "s")
(depends-on "scala-mode2")
(depends-on "slime")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "virtualenv")
(depends-on "wrap-region")
(depends-on "yasnippet")